version: '3.8'

services:
  customer_order_tracking:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../frontend:/frontend
      - ../backend:/app  # Mount backend to /app in the container
    ports:
      - "8081:5000"
    depends_on:
      - customer_order_kafka
      - customer_order_zookeeper
      - customer_order_mysql
    environment:
      - FLASK_ENV=production
    command: >
      sh -c "pip install -r requirements.txt &&
             flask run --host=0.0.0.0 --port=5000"

  customer_order_kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://customer_order_kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: customer_order_kafka:2181
    depends_on:
      - customer_order_zookeeper

  customer_order_zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  customer_order_mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xyz1234
      MYSQL_DATABASE: customer_order_tracking
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
